# Generated by Django 3.1.5 on 2021-01-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_auto_20210124_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
