# Generated by Django 3.1.5 on 2021-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='usuario')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('rol', models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario'), ('3', 'Otros')], max_length=1, verbose_name='rol')),
            ],
        ),
    ]
